simulator {
  enricher {
    gen-output-file-path = ${simulator.outputDirectory}"generated/override.ngs"
    topology = "ring"
    messages = ["Election", "Ping", "Pong", "Work", "Ack"]
    nodes {
      distribution {
        type = "Uniform"
      }
      seed = 42
      default-pdf = {"Ping": 0.3, "Work": 0.7}
      overrides = [
        {id = 3, is-input = true},
        {id = 7, tick-interval-ms = 5000},
        {id = 2, tick-interval-ms = 10000},
        {id = 5, is-input = true, pdf = {"Work": 1.0}},
        {id = 10, is-input = true}
      ]
    }
    edges {
      default-allowed-messages = ${simulator.enricher.messages}
      overrides = [
        {from: 4, to: 2, allow=["Work"]},
        {from: 8, to: 10, allow=[]},
        {from: 10, to: 7, allow=["Work"]}
      ]
    }
  }
}