NGSimulator {
  seed = 100
  outputDirectory = ${user.dir}/"output/generated"
  NetModel {
    distanceSpreadThreshold = 0.0
    numberOfExperiments = 1
    perturbationCoefficient = 0.01
    dissimulationCoefficient = 0.0
    distanceCoefficient = 0.0
    edgeProbability = 0.0
    statesTotal = 10
    desiredReachabilityCoverage = 1.0
    numberOfWalks = 0
    maxBranchingFactor = 1
    maxDepth = 1
    maxProperties = 1
    propValueRange = 1
    actionType = 1
    actionRange = 1
    connectedness = 1
    maxWalkPathLengthCoeff = 2
    graphWalkTerminationPolicy = ${NGSimulator.Constants.MaxPathLength}
    graphWalkNodeTerminationProbability = 0.0d
    valuableDataProbability = 0.0d
  }
  CostRewards {
    malAppBudget = 2700.0
    costOfDetection = 0.2d
    serviceRewardProbability = 0.3
    serviceReward = 10d
    servicePenalty = 3d
    targetAppScore = 5
    targetAppLowPenalty = 1
    targetAppHighPenalty = 2
  }
  Constants {
    MaxPathLength  = "maxpathlength"
    UntilCycle = "untilcycle"
    All = "all"
  }
  Graph {
    directionality = "directed"
    fileName = "NetGameSimNetGraph_29-10-23-00-22-06.ngs"
    outputPath = "./converted"
    graphLocation = "../../../"
  }
  # change contentType to "json" for json representation of generated ngs file
  OutputGraphRepresentation {
    contentType = "json"
  }
}