NGSimulator {
  seed = 100
  outputDirectory = ${user.dir}/"output/experiments/generated"

  NetModel {
    distanceSpreadThreshold = 0.2
    numberOfExperiments = 1
    perturbationCoefficient = 0.01
    dissimulationCoefficient = 0.0
    distanceCoefficient = 0.0
    edgeProbability = 0.15
    statesTotal = 15
    desiredReachabilityCoverage = 1.0
    numberOfWalks = 0
    maxBranchingFactor = 3
    maxDepth = 3
    maxProperties = 20
    propValueRange = 100
    actionType = 20
    actionRange = 10
    connectedness = 2
    maxWalkPathLengthCoeff = 1
    graphWalkTerminationPolicy = ${NGSimulator.Constants.UntilCycle}
    graphWalkNodeTerminationProbability = 0.0d
    valuableDataProbability = 0.0d
  }

  CostRewards {
    malAppBudget = 2700.0
    costOfDetection = 0.2d
    serviceRewardProbability = 0.3
    serviceReward = 10d
    servicePenalty = 3d
    targetAppScore = 5
    targetAppLowPenalty = 1
    targetAppHighPenalty = 2
  }

  Constants {
    MaxPathLength  = "maxpathlength"
    UntilCycle = "untilcycle"
    All = "all"
  }

  Graph {
    directionality = "undirected"
    fileName = "tree.ngs"
    outputPath = "./converted"
    graphLocation = "../../../"
  }

  OutputGraphRepresentation {
    contentType = "json"
  }
}