simulator {
  generator {
    jarPath = ${user.dir}/"core/generator/target/scala-3.2.2/netmodelsim.jar"
    minimumMemory = 2
    maximumMemory = 4
    ngsConfigPath = ${user.dir}/"core/src/main/resources/gen-chain.conf"
    outputFileName = "override"
  }
}