simulator {
  outputDirectory = ${user.dir}/"output/experiments/"
  generator {
    jarPath = ${user.dir}/"core/generator/target/scala-3.2.2/netmodelsim.jar"
    minimumMemory = 2
    maximumMemory = 4
    ngsConfigPath = ${user.dir}/"core/src/main/resources/gen-chain.conf"
    outputFileName = "exp-hs"
  }
  enricher {
    gen-output-file-path = ${simulator.outputDirectory}/"generated"/${simulator.generator.outputFileName}".ngs"
    topology = "ring"
    messages = ["Election", "Ping", "Pong", "Work", "Ack"]
    nodes {
      distribution {
        type = "Uniform"
      }
      seed = 42
      default-pdf = {"Ping": 0.3, "Work": 0.7}
      overrides = [
        {id = 3, is-input = true, pdf={"Work": 0.3, "Ping": 0.7}},
        {id = 7, tick-interval-ms = 5000},
        {id = 2, tick-interval-ms = 10000},
        {id = 5, is-input = true, pdf={"Work": 1}},
        {id = 10, is-input = true}
      ]
    }
    edges {
      default-allowed-messages = ${simulator.enricher.messages}
      overrides = [
        {from: 2, to: 5, allow=["Work", "Election"]},
        {from: 7, to: 8, allow=["Election"]},
        {from: 10, to: 9, allow=["Work", "Election"]}
      ]
    }
    enriched-output-file-path = ${simulator.outputDirectory}"enriched/exp-hs"
  }
  translator {
    enriched-output-file-path = ${simulator.enricher.enriched-output-file-path}".sim",
    inject-file-path = ${user.dir}/"input/input.json"
  }
}

cinnamon.chmetrics {
  reporters = ["slf4j-reporter"]

  slf4j-reporter {
    output-to = "cinnamon.metrics"
    frequency = 5s
  }
}

cinnamon.akka {
  actors {
    "/user/*" {
      report-by = instance
    }
  }
}